name: GitHub Test 1
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install
      - name: "Run Test"
        run: npm test




