name: GitHub Test 1
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: kms_sose22_grp1
      DB_USER: 'root'
      DB_PASSWORD: 'root'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install mocha
        run: npm i @types/mocha mocha
      - name: Install dependencies
        run: npm ci
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql> use kms_sose22_grp1
          mysql> source aufgaben.sql
      - name: "Run Test"
        run: npm test




